#!/bin/bash

# Bash script to align RNA-seq reads using STAR for multiple samples

# Author: [Qiulin Huang]
# Date: [241015]

# ==============================
# User-defined variables
# ==============================

# Number of threads to use for STAR
THREADS=12

# Directory containing the genome indices generated by STAR
GENOME_DIR="/storage/Qiulin/Bioinformatics/Bulk_RNA-seq/STAR_Index/STAR_Index"

# Directory where your raw FASTQ files are located
RAW_DATA_DIR="/storage/Qiulin/Bioinformatics/Bulk_RNA-seq/RN24191/20250207_and_20250221_concat"

# Directory to store the alignment outputs
OUTPUT_DIR="/storage/Qiulin/Bioinformatics/Bulk_RNA-seq/RN24191/20250207_and_20250221_concat/Alignment_Output"

# Specify read file extensions
READ1_EXT="_R1.fastq.gz"
READ2_EXT="_R2.fastq.gz"

# ==============================
# Create output directory if it doesn't exist
# ==============================

mkdir -p "${OUTPUT_DIR}"

# ==============================
# Loop through each sample and perform alignment
# ==============================

for i in {5..22}; do
    SAMPLE="HUA7170A${i}"
    echo "Processing ${SAMPLE}..."

    # Define input read files
    READ1="${RAW_DATA_DIR}/${SAMPLE}${READ1_EXT}"
    READ2="${RAW_DATA_DIR}/${SAMPLE}${READ2_EXT}"

    # Check if input files exist
    if [[ ! -f "${READ1}" ]] || [[ ! -f "${READ2}" ]]; then
        echo "Error: One or both input files for ${SAMPLE} are missing."
        continue
    fi

    # Define output prefix
    OUT_PREFIX="${OUTPUT_DIR}/${SAMPLE}_"

    # Run STAR alignment
    /storage/aer79/programs/STAR-2.7.11b/bin/Linux_x86_64/STAR --runThreadN ${THREADS} \
         --genomeDir "${GENOME_DIR}" \
         --readFilesIn "${READ1}" "${READ2}" \
         --readFilesCommand zcat \
         --outFileNamePrefix "${OUT_PREFIX}" \
         --outSAMtype BAM SortedByCoordinate \
         --quantMode GeneCounts \
         --twopassMode Basic

    # Check if STAR ran successfully
    if [[ $? -ne 0 ]]; then
        echo "STAR alignment failed for ${SAMPLE}."
        continue
    fi

    echo "Alignment completed for ${SAMPLE}."
done

echo "All samples processed."
